In [16]:
from intReader import IntensityBin
import os

In [2]:
file = "/home/sih13/Downloads/C001R006.int"

In [3]:
ib = IntensityBin(file)

In [4]:
cycle_ints = ib.metrics.IntsData.reshape(ib.metrics.ChannelNumber, -1).T

In [5]:
cycle_ints.shape

(1408077, 4)

In [6]:
ib.metrics.NormalizationValue

array([ -44.4055, 1299.5101,  -43.1218, 1313.4534,  -75.6384, 1758.4504,
        -41.9453, 1094.7599,    0.    ,    0.9946,    0.    ,    0.7541,
          0.    ,    0.7759,    0.    ,    1.0525], dtype=float32)

In [12]:
the_other = "/home/sih13/mnt/zebra/V350003488_6fov/L03/finInts/S005/C005R048.int"

In [13]:
ib_2 = IntensityBin(the_other)

In [14]:
ib_2.metrics.NormalizationValue

array([-151.2014, 3519.726 ,    0.8502,  -95.4611, 2671.502 ,    0.6895,
       -150.591 , 3211.7537,    0.7321,  -96.6854, 1993.4944,    0.735 ,
          0.    ,    1.    ,    0.    ,    1.    ], dtype=float32)

In [15]:
for i, cycle in enumerate(8):
    int_bin_fp = os.path.join(data_dp, self.int_type, 'S%03d' % cycle, '%s.int' % self.fov)


array([[ 781.3875, 1319.9375, 1078.9375,  897.65  ],
       [ 757.625 , 1343.25  , 1079.4875,  882.8375],
       [ 702.5625, 1292.125 , 1007.5625,  807.0625],
       [ 667.4375, 1144.75  ,  901.375 ,  751.4375],
       [ 602.75  ,  979.4375,  774.875 ,  657.3125],
       [ 538.    ,  908.3125,  704.4375,  578.0625],
       [ 550.8125,  962.0625,  704.625 ,  599.9375],
       [ 576.125 ,  998.3125,  726.9375,  609.    ],
       [ 569.8375,  955.55  ,  727.65  ,  614.1   ],
       [ 556.475 ,  920.85  ,  707.6375,  621.1625],
       [ 771.6375, 1278.625 , 1010.5125,  863.1875],
       [ 769.    , 1282.    , 1001.    ,  862.25  ],
       [ 744.75  , 1230.    ,  949.25  ,  829.    ],
       [ 690.25  , 1107.    ,  874.5   ,  757.75  ],
       [ 594.5   ,  975.25  ,  790.    ,  633.75  ],
       [ 536.5   ,  888.5   ,  718.5   ,  575.    ],
       [ 547.5   ,  933.5   ,  709.75  ,  608.    ],
       [ 573.    ,  961.25  ,  725.75  ,  614.    ],
       [ 566.5   ,  914.25  ,  710.5   ,  611.

In [17]:
ziqing = "/home/sih13/mnt/C004R036.int"

ib_3 = IntensityBin(ziqing)

ib_3.metrics.NormalizationValue

array([-296.4025, 3613.2593, -168.6329, 2352.18  , -154.2334, 1932.9615,
       -225.6561, 2607.9   ,    0.    ,    0.9803,    0.    ,    0.7729,
          0.    ,    0.8155,    0.    ,    0.9663], dtype=float32)